schema-version: v1
kind: stack
metadata:
  name: stack-infra
  display-name: stack-infra
  description: Descreva a stack explicando o seu propósito
  version: 0.0.1
spec:
  docs:
    en-us: docs/en_us/docs.md
    pt-br: docs/pt_br/docs.md
  repository: git@github.com:fabianofernandeszup/chiaretto-studio.git
  plugins:
    infra:
      - name: chiaretto-studio/plugin-infra-v2-app-allowed-false@0.0.1
      - name: chiaretto-studio/plugin-infra-v2-app-allowed-true@0.0.1
      - name: chiaretto-studio/plugin-infra-v2-basico@1.0.0
      - name: chiaretto-studio/plugin-infra-v2-completo@1.0.0
      - name: chiaretto-studio/plugin-infra-v2-inputs-contexto@0.0.6
      - name: chiaretto-studio/plugin-infra-v2-links-gen-req@0.0.2
      - name: chiaretto-studio/plugin-infra-v2-links-req@0.0.2
      - name: chiaretto-studio/plugin-infra-v2-no-req-gen-s3@0.0.1
      - name: chiaretto-studio/plugin-infra-v2-req-sm-gen-s3@0.0.1
      - name: chiaretto-studio/plugin-infra-v2-without-app-allowed@0.0.2
      - name: chiaretto-studio/plugin-infra-v3-novos-inputs@1.0.0
  actions:
    - name: chiaretto-studio/action-v2-convert-content-v1-to-v2@0.0.1
    - name: chiaretto-studio/action-v2-create-repo-github-and-set-secret-cred-stackspot@1.0.0
    - name: chiaretto-studio/action-v2-req-conn-rds@1.0.5
    - name: chiaretto-studio/action-v2-req-conn-sns@0.0.1
    - name: chiaretto-studio/action-v2-set-credencial-stackspot-new-repo@0.0.1
    - name: chiaretto-studio/action-v2-vazia-sem-inputs-python@0.0.1
    - name: chiaretto-studio/action-python-v3-novos-inputs@0.0.1
  starters:
    - path: starters/starter-novos-inputs
