schema-version: v1
kind: stack
metadata:
  name: stack-infra
  display-name: stack-infra
  description: Descreva a stack explicando o seu propósito
  version: 0.0.1
spec:
  repository: git@github.com:fabianofernandeszup/chiaretto-studio.git
  docs:
    en-us: docs/en_us/docs.md
    pt-br: docs/pt_br/docs.md
  actions:

  plugins:
    app:

    infra:
