schema-version: v1
kind: stack
metadata:
  name: stack-infra
  display-name: stack-infra
  description: Descreva a stack explicando o seu propósito
  version: 0.0.1
spec:
  repository: git@github.com:fabianofernandeszup/chiaretto-studio.git
  docs:
    en-us: docs/en_us/docs.md
    pt-br: docs/pt_br/docs.md
  actions:
    - name: cli-studio-eng/action-v2-vazia-sem-inputs-python@0.0.1
    - name: cli-studio-eng/stakspot-github-create-repository@1.0.0
  plugins:
    infra:
      - name: cli-studio-eng/plugin-infra-v2-links-req@0.0.2
      - name: cli-studio-eng/plugin-infra-v2-links-gen-req@0.0.2
