schema-version: v3
kind: action
metadata:
  name: action-generate-json-schema-stackspot
  display-name: action-generate-json-schema-stackspot
  description: Descreva sua action explicando o propósito.
  version: 0.0.1
spec:
  type: python
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  repository: git@github.com:fabianofernandeszup/chiaretto-studio.git
  inputs:
    - label: What is your name?
      name: user_name
      type: text
      required: false
      pattern: '^[A-Za-z]+(?:\s[A-Za-z]+)*$'
      help: 'Inform your name'
  python:
    workdir: .
    script: script.py
