schema-version: v2
kind: action
metadata:
  name: action-schema-v2-create-repo-github
  display-name: action-schema-v2-create-repo-github
  description: Descreva sua action explicando o propósito
  version: 0.0.1
spec:
  type: python
  about: docs/about.md
  usage: docs/usage.md
  release-notes: docs/release-notes.md
  requirements: docs/requirements.md
  implementation: docs/implementation.md
  repository: git@github.com:fabianofernandeszup/chiaretto-studio.git
  inputs:
    - label: Visibility
      name: visibility
      type: text
      required: true
      items:
        - public
        - internal
        - private
      help: "Internal repo can only be created by enterprise accounts."
  python:
    workdir: .
    script: script.py
