schema-version: v2
kind: action
metadata:
  name: action-schema-v2-create-repo-github
  display-name: action-schema-v2-create-repo-github
  description: Descreva sua action explicando o propósito
  version: 0.0.2
spec:
  type: python
  docs:
    pt-br: docs/pt_br/doc.md
    en-us: docs/en_us/doc.md
  repository: git@github.com:fabianofernandeszup/chiaretto-studio.git
  inputs:
    - label: Visibility
      name: visibility
      type: text
      required: true
      default: private
      items:
        - public
        - internal
        - private
      help: Internal repo can only be created by enterprise accounts.
  python:
    workdir: .
    script: script.py
