schema-version: v1
kind: action
metadata:
  name: action-rci-rds
  display-name: action-require-connection-interface-rds
  description: Describe your action explaining its purpose 4
  version: 1.0.4
spec:
  type: python
  docs:
    pt_br: docs/pt_br/doc.md
    en_us: docs/en_us/doc.md
  requires:
    connection-interface:
      - aws-rds-conn
  inputs:
    - label: Who are you?
      name: user_name
      type: text
      required: true
      help: Inform your name
  python:
    workdir: .
    script: script.py
