schema-version: v1
kind: action
metadata:
  name: action-rci-rds
  display-name: action-require-connection-interface-rds
  description: Describe your action explaining its purpose
  version: 1.0.4
spec:
  type: python
  about: docs/about.md
  usage: docs/usage.md
  release-notes: docs/release-notes.md
  requirements: docs/requirements.md
  implementation: docs/implementation.md
  requires:
    connection-interface:
      - aws-rds-conn
  inputs:
    - label: Who are you?
      name: user_name
      type: text
      required: true
      help: 'Inform your name'
  python:
    workdir: .
    script: script.py
