schema-version: v1
kind: action
metadata:
  name: action-vazia-sem-inputs-python
  display-name: action-vazia-sem-inputs-python
  description: Describe your action explaining its purpose
  version: 0.0.1
spec:
  type: python
  docs:
    pt_br: docs/pt_br/doc.md
    en_us: docs/en_us/doc.md
  python:
    workdir: .
    script: script.py
