schema-version: v2
kind: action
metadata:
  name: action-vazia-sem-inputs-python
  display-name: action-vazia-sem-inputs-python
  description: Describe your action explaining its purpose
  version: 0.0.1
spec:
  type: python
  docs:
    pt-br: docs/pt-br/doc.md
    en-us: docs/en-us/doc.md
  python:
    workdir: .
    script: script.py
