schema-version: v1
kind: action
metadata:
  name: action-vazia-sem-inputs-python
  display-name: action-vazia-sem-inputs-python
  description: Describe your action explaining its purpose
  version: 0.0.1
spec:
  type: python
  about: docs/about.md
  usage: docs/usage.md
  release-notes: docs/release-notes.md
  requirements: docs/requirements.md
  implementation: docs/implementation.md
  python:
    workdir: .
    script: script.py
