schema-version: v2
kind: action
metadata:
  name: set-credencial-stackspot-new-repo
  display-name: set-credencial-stackspot-new-repo
  description: Descreva sua action explicando o propósito
  version: 0.0.1
spec:
  type: shell
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  repository: git@github.com:fabianofernandeszup/chiaretto-studio.git
  inputs:
    - label: Type some label
      name: random-name
      type: text
      required: false
      pattern: '([A-Z][a-z]+)+'
      help: 'Inform your resource name (e.g.: Client)'
  shell:
    workdir: .
    requirements-check:
      - check-command:
          linux: |
            echo "Hello World!"
          mac: |
            echo "Hello World!"
          windows: |
            echo "Hello World!"
        info: "Failed saying hello to world."
    script:
      linux: |
        echo "Hello World!"
      mac: |
        echo "Hello World!"
      windows: |
        echo "Hello World!"
