schema-version: v2
kind: action
metadata:
  name: set-credencial-stackspot-new-repo
  display-name: set-credencial-stackspot-new-repo
  description: Descreva sua action explicando o propósito
  version: 0.0.1
spec:
  type: python
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  repository: git@github.com:fabianofernandeszup/chiaretto-studio.git
  inputs:
    - label: Who are you?
      name: user_name
      type: text
      required: false
      pattern: '([A-Z][a-z]+)+'
      help: 'Inform your name'
  python:
    workdir: .
    script: script.py
