schema-version: v2
kind: action
metadata:
  name: action-v2-create-repo-github
  display-name: action-v2-create-repo-github
  description: Action to create github repository
  version: 1.0.0
spec:
  type: python
  docs:
    pt-br: docs/pt_br/doc.md
    en-us: docs/en_us/doc.md
  inputs:
    - label: Visibility
      name: visibility
      type: text
      required: true
      items:
        - public
        - internal
        - private
      help: Internal repo can only be created by enterprise accounts.
  python:
    workdir: .
    script: script.py
