schema-version: v1
kind: stack
metadata:
  name: stack-app-plugin-basico-workflow-create-starter
  display-name: stack-app-plugin-basico-workflow-create-starter
  description: Descreva a stack explicando o seu propósito.
  version: 0.0.1
spec:
  repository: git@github.com:fabianofernandeszup/chiaretto-studio.git
  docs:
    en-us: docs/en_us/docs.md
    pt-br: docs/pt_br/docs.md
  plugins:
    app:
      - name: cli-studio-eng/plugin-app-v3-basico@0.0.1
  workflows:
    - name: cli-studio-eng/workflow-create-app-com-starter-app-com-um-plugin-basico@0.0.1
    - name: cli-studio-eng/workflow-starter-app-um-plugin-basico@0.0.1
