schema-version: v1
kind: plugin
metadata:
  name: plugin-infra-gen-rds-req-eks
  display-name: plugin-infra-gen-rds-req-eks
  description: Describe your plugin explaining its purpose
  version: 1.0.0
  picture: plugin.png
spec:
  type: infra
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
    - Api
  generates:
    connection-interface:
      - aws-rds-conn
  requires:
    connection-interface:
      - aws-eks-conn
  inputs:
    - label: Type name of RDS
      name: resource
      type: text
      required: true