name: Publish

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  PUBLISH:
    environment: 'prd-eng'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Check changes
        uses: dorny/paths-filter@v2
        id: filter_shell
        with:
          list-files: shell
          filters: |
            content:
              - './actions/**'
              - './plugins/**'
              - '.github/workflows/**'

      - name: Install STK CLI
        run: |
          curl -fsSL https://stk.stackspot.com/install.sh | bash
          ~/.stk/bin/stk upgrade

      - name: Version STK CLI
        run: |
          ~/.stk/bin/stk --version

      - name: Publish Plugins
        run: |
          ~/.stk/bin/stk login --client-id $STK_CLIENT_ID --client-key $STK_CLIENT_KEY --realm $STK_REALM

          arrAllFilesChanged=(${{ steps.filter_shell.outputs.content_files }})
          arrAllDirs=()
          ################# Check File or dir #########################
          for counter in ${!arrAllFilesChanged[*]}; do
            echo "Check file ${{ github.workspace }}/${arrAllFilesChanged[counter]}"
            if [[ -d "${{ github.workspace }}/${arrAllFilesChanged[counter]}" ]]; then
                arrAllDirs=(${arrAllDirs[@]} "${{ github.workspace }}/${arrAllFilesChanged[counter]}")
            else
                arrAllDirs=(${arrAllDirs[@]} "${{ github.workspace }}/${arrAllFilesChanged[counter]%/*}")
            fi
          done

          ###### Filter Uniq Dir #########
          readarray -t arrAllDirs < <(printf '%s\n' "${arrAllDirs[@]}" | sort -u)

          ###### Publish #########
          for i in ${arrAllDirs[@]}; do
            if [[ -f "${i}/plugin.yaml" ]]; then
              cd $i
              ~/.stk/bin/stk publish plugin --studio $STK_STUDIO || true
            fi
            if [[ -f "${i}/action.yaml" ]]; then
              cd $i
              ~/.stk/bin/stk publish action  --studio $STK_STUDIO || true
            fi
          done

        env:
          STK_REALM: ${{ vars.stk_realm }}
          STK_STUDIO: ${{ vars.stk_studio }}
          STK_CLIENT_ID: ${{ secrets.stk_client_id }}
          STK_CLIENT_KEY: ${{ secrets.stk_client_key }}