name: Publish

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_changes:
    environment: 'prd-eng'
    runs-on: ubuntu-20.04
    outputs:
      has-plugins: ${{ steps.files.outputs.has-plugins }}
      dirs-plugins: ${{ steps.files.outputs.dirs-plugins }}
      has-actions: ${{ steps.files.outputs.has-actions }}
      dirs-actions: ${{ steps.files.outputs.dirs-actions }}
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Check changes
        uses: dorny/paths-filter@v2
        id: filter_shell
        with:
          list-files: shell
          filters: |
            content:
              - './actions/**'
              - './plugins/**'
              - '.github/workflows/**'

      - name: Check Plugins and Actions
        id: files
        run: |
          arrAllFilesChanged=(${{ steps.filter_shell.outputs.content_files }})
          arrAllDirs=()
          ################# Check File or dir #########################
          for counter in ${!arrAllFilesChanged[*]}; do
            if [[ -d "${{ github.workspace }}/${arrAllFilesChanged[counter]}" ]]; then
                arrAllDirs=(${arrAllDirs[@]} "${arrAllFilesChanged[counter]}")
            else
                arrAllDirs=(${arrAllDirs[@]} "${arrAllFilesChanged[counter]%/*}")
            fi
          done

          ###### Filter Uniq Dir #########
          readarray -t arrAllDirs < <(printf '%s\n' "${arrAllDirs[@]}" | sort -u)

          ###### Publish #########
          arrPluginsDir=()
          arrActionsDir=()
          for i in ${arrAllDirs[@]}; do
            if [[ -f "${{ github.workspace }}/${i}/plugin.yaml" ]]; then
              arrPluginsDir=(${arrPluginsDir[@]} "${i}")
              echo "has-plugins=true" >> "$GITHUB_OUTPUT"
            fi
            if [[ -f "${{ github.workspace }}/${i}/action.yaml" ]]; then
              arrActionsDir=(${arrActionsDir[@]} "${i}")
              echo "has-actions=true" >> "$GITHUB_OUTPUT"
            fi
          done

          echo "dirs-plugins=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${arrPluginsDir[@]}")" >> "$GITHUB_OUTPUT"
          echo "dirs-actions=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${arrActionsDir[@]}")" >> "$GITHUB_OUTPUT"

  install_stk:
    if: needs.check_changes.outputs.has-plugins == 'true' || needs.check_changes.outputs.has-actions == 'true'
    runs-on: ubuntu-latest
    environment: 'prd-eng'
    needs: check_changes
    steps:
      - name: Install STK CLI
        run: |
          curl -fsSL https://stk.stackspot.com/install.sh | bash
          ~/.stk/bin/stk upgrade

      - name: Version STK CLI
        run: |
          ~/.stk/bin/stk --version

      - name: Login
        run: ~/.stk/bin/stk login --client-id $STK_CLIENT_ID --client-key $STK_CLIENT_KEY --realm $STK_REALM
        env:
          STK_REALM: ${{ vars.stk_realm }}
          STK_STUDIO: ${{ vars.stk_studio }}
          STK_CLIENT_ID: ${{ secrets.stk_client_id }}
          STK_CLIENT_KEY: ${{ secrets.stk_client_key }}

      - name: Cache STK Cli
        uses: actions/cache/save@v3
        with:
          path: ~/.stk
          key: ${{ github.run_id }}-stk

  publish_plugins:
    if: needs.check_changes.outputs.has-plugins == 'true'
    runs-on: ubuntu-latest
    environment: 'prd-eng'
    needs:
      - install_stk
      - check_changes
    strategy:
      matrix:
        dir: ${{ fromJson(needs.check_changes.outputs.dirs-plugins) }}
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Restore STK CLI
        uses: actions/cache/restore@v3
        with:
          path: ~/.stk
          key: ${{ github.run_id }}-stk

      - run: |
          echo "Plugin ${{ github.workspace }}/${{ matrix.dir }}"
          cd ${{ github.workspace }}/${{ matrix.dir }}
          ~/.stk/bin/stk publish plugin --studio $STK_STUDIO
        env:
          STK_STUDIO: ${{ vars.stk_studio }}

  publish_actions:
    if: needs.check_changes.outputs.has-actions == 'true'
    runs-on: ubuntu-latest
    environment: 'prd-eng'
    needs:
      - install_stk
      - check_changes
    strategy:
      matrix:
        dir: ${{ fromJson(needs.check_changes.outputs.dirs-actions) }}
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Restore STK CLI
        uses: actions/cache/restore@v3
        with:
          path: ~/.stk
          key: ${{ github.run_id }}-stk

      - run: |
          echo "Plugin ${{ github.workspace }}/${{ matrix.dir }}"
          cd ${{ github.workspace }}/${{ matrix.dir }}
          ~/.stk/bin/stk publish action --studio $STK_STUDIO
        env:
          STK_STUDIO: ${{ vars.stk_studio }}