name: Publish

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  PUBLISH:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Check changes
        uses: dorny/paths-filter@v2
        id: filter_shell
        with:
          list-files: shell
          filters: | # set ${{ steps.filter.outputs.workflows }} == 'true'
            content:
              - './actions/**'
              - './plugins/**'
              - '.github/workflows/**'

      - name: Check changes
        uses: dorny/paths-filter@v2
        id: filter_json
        with:
          list-files: json
          filters: | # set ${{ steps.filter.outputs.workflows }} == 'true'
            content:
              - './actions/**'
              - './plugins/**'
              - '.github/workflows/**'

      - name: Install STK CLI
        run: curl -fsSL https://stk-dev.stackspot.com/install-alpha.sh | bash

      - name: Publish Plugins
        run: |
          stk-alpha login --client-id $STK_CLIENT_ID --client-key $STK_CLIENT_KEY --realm $STK_REALM
          echo "##########################################"
          echo ${{ steps.filter_shell.outputs.content }}
          echo "##########################################"
          echo ${{ steps.filter.filter_json.content }}
        env:
          STK_REALM: ${{ vars.stk_realm }}
          STK_CLIENT_ID: ${{ secrets.stk_client_id }}
          STK_CLIENT_KEY: ${{ secrets.stk_client_key }}