name: Test

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version_stk:
    runs-on: ubuntu-latest
      container:
        image: stackspot/stk-cli-ubuntu:5.7.2
    steps:
      - name: Version STK CLI
        run: |
          ~/.stk/bin/stk --version