name: Test

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container:
      image: stackspot/stk-cli-ubuntu:5.7.2
    steps:
      - name: Version STK CLI
        run: |
          pwd
          cd ~
          pwd
          cd /home/stk/.stk/bin
          ls -lha
          chmod +x /home/stk/.stk/bin/stk
          ./home/stk/.stk/bin/stk -v